# Generated by Django 4.2.5 on 2023-09-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default=1321231, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
